### ISSUE TITLE
Add PatternEngine-specific configs

### ISSUE THREAD

**Issue by TxHawks** [pattern-lab/edition-php-twig-development#11]
It could be useful to add config options for setting the default date format and timezone to be used with the `date` filter and function. 

Twig documentation states that if no format is provided, Twig will use the default one: `F j, Y H:i`. This default can be easily changed by calling the `setDateFormat()` method on the core extension instance. The first argument is the default format for dates and the second one is the default format for date intervals:

```php
$twig = new Twig_Environment($loader);
$twig->getExtension('core')->setDateFormat('d/m/Y', '%d days');
```
And that the default timezone can also be set globally by calling `setTimezone()`:

```php
$twig = new Twig_Environment($loader);
$twig->getExtension('core')->setTimezone('Europe/Paris');
```
See http://twig.sensiolabs.org/doc/filters/date.html

**Comment by dmolsen** [comment]
K. I guess we need PatternEngine-specific configs then. Noted for the [beta](https://github.com/pattern-lab/edition-php-twig-development/issues/10) as well.

**Comment by TxHawks** [comment]
It would also be nice to add a config that will `dump()` function available, as [according to the docs](http://twig.sensiolabs.org/doc/functions/dump.html), it is not available by default:

The `dump` function is not available by default. You must add the `Twig_Extension_Debug` extension explicitly when creating your Twig environment:

```php
$twig = new Twig_Environment($loader, array(
    'debug' => true,
    // ...
));
$twig->addExtension(new Twig_Extension_Debug());
```

Even when enabled, the dump function won't display anything if the `debug` option on the environment is not enabled (to avoid leaking debug information on a production server).

**Comment by dmolsen** [comment]
Noted. Keep the feedback coming :)

**Comment by dmolsen** [comment]
Both of these have been added. To update run:

    composer update pattern-lab/patternengine-twig

The config options should be automatically added to `configs/config.yml`. Note that debug is set to `false` by default so your template will blow up if you try to se that before setting it to `true`. Leaving the formats blank will tell Twig to use its regular defaults.

**Comment by glassdimly** [comment]
Hmm. I don't see how to enable the debug environment. I've tried simply: `debug: 'true'` as you suggest in `config/config.yml` but I still get an error when I use `dump()` in a twig file.

**Comment by glassdimly** [comment]
Nevermind. Found this setting here: https://github.com/pattern-lab/patternengine-php-twig#enable-dump

`twigDebug : 'true'`
