### ISSUE TITLE
Install fails, requirements could not be resolved

### ISSUE THREAD

**Issue by vitaminless** [pattern-lab/edition-php-twig-development#13]
The installation as described in the Readme fails:
```
$ composer create-project pattern-lab/edition-development-twig edition-development-twig                                                                                                                                            Mo  2 Mär 2015 09:40:15 CET
Installing pattern-lab/edition-development-twig (v0.1.0)
  - Installing pattern-lab/edition-development-twig (v0.1.0)
    Loading from cache

Created project in edition-development-twig
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - pattern-lab/styleguidekit-assets-default dev-dev requires pattern-lab/core ~0.5 -> no matching package found.
    - pattern-lab/styleguidekit-twig-default dev-dev requires pattern-lab/styleguidekit-assets-default dev-dev -> satisfiable by pattern-lab/styleguidekit-assets-default[dev-dev].
    - Installation request for pattern-lab/styleguidekit-twig-default dev-dev -> satisfiable by pattern-lab/styleguidekit-twig-default[dev-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by dmolsen** [comment]
@vitaminless -

Sorry about that. I was trying to set-up a [true beta version of the Twig work](https://github.com/pattern-lab/edition-php-twig-standard) but messed up the dependencies. What's odd is that `pattern-lab/core` definitely has `v0.5`+ tags. I'm going to play with this a little bit this morning. Hopefully I can resolve it quickly.

**Comment by dmolsen** [comment]
@vitaminless -

Had this working again this morning but have run into another issue with the latest edition of Composer. You can try to install but let me know if it blows up for you too.

**Comment by dmolsen** [comment]
@vitaminless -

You should be able to install now. You should run the following before attempting to install the project though:

    composer self-update

Please note that the Development Edition should be considered unstable. If you use it you will essentially always be running edge when you update your project components. The developer preview for the stable [Standard Edition for Twig](https://github.com/pattern-lab/edition-php-twig-standard) should be out today or tomorrow.

**Comment by vitaminless** [comment]
Sorry for late response, true it works now
