### ISSUE TITLE
Update Composer Installer Events

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/edition-php-twig-development#16]
@bradfrost @txhawks -

The latest edition of Composer broke the package install and update process. I've tweaked it in core. Before you run your next updates to your projects please do the following:

1. run `composer self-update`
2. copy over `core/src/PatternLab/Installer.php` with the [code from here](https://raw.githubusercontent.com/pattern-lab/edition-php-twig-development/master/core/src/PatternLab/Installer.php)
3. run `composer update pattern-lab/core`

I'll leave this issue open for a bit in case you have questions.

PS - I'm making sure that the standard edition can be installed sans Composer. Updates and plug-in installs will require it but at least someone should be able to get up and running without worrying about this stuff.

**Comment by TxHawks** [comment]
@dmolsen - 
Thanks for the heads up. 

How about installing new instances?

**Comment by dmolsen** [comment]
@TxHawks -

Since I've updated the code in GitHub and new instances will pull from that code we're good to go.

**Comment by TxHawks** [comment]
For future reference:
I got an ugly error message complaining about PHP's curl extension when trying to run `composer update` on a Ubuntu box.

This can be solved by running `sudo apt-get update && sudo apt-get install php5-curl` before running `composer update pattern-lab/core`
