### ISSUE TITLE
Segmentation fault when running php core/console --help

### ISSUE THREAD

**Issue by TxHawks** [pattern-lab/edition-php-twig-development#2]
When running `php core/console --help` on a Ubuntu 14.04 box, after running `php core/console --generate` as per the instructions in the `README.md`, I get the following output:
````
configuring pattern lab...                                           
                                                                     
[1]    7428 segmentation fault (core dumped)  php core/console --help
````

On a side note, `composer create-project pattern-lab/edition-development-twig project-name && cd $_` didn't prompt `Do you want to remove the existing VCS (.git, .svn..) history?`

**Comment by dmolsen** [comment]
Version of PHP? I've had problems with Ubuntu in the past. For example, JSON isn't/wasn't included by default in some distros because the license wasn't "free" enough. Just want to double-check that kind of compatibility issue. My hunch is that this is related to the colored output feature.

**Comment by dmolsen** [comment]
Well... can you run any command? e.g. `--generate`

**Comment by TxHawks** [comment]
both `--generate` and `--server` seem to work.

Here is the output of `php -v`:
````
PHP 5.5.9-1ubuntu4.6 (cli) (built: Feb 13 2015 19:17:11)                   
Copyright (c) 1997-2014 The PHP Group                                      
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies              
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
````

**Comment by TxHawks** [comment]
Just so I can continue configuring my stack until this is resolved - is `console -gp` the same as `builder.php -gp` used to be?

**Comment by dmolsen** [comment]
Yup

**Comment by dmolsen** [comment]
Confirming this issue on 5.5.14 too. My error is a little more descriptive:

```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in /{path}/patternlab-project/test/test-twig/vendor/kevinlebrun/colors.php/src/Colors/Color.php on line 197

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in /{path}/patternlab-project/test/test-twig/vendor/kevinlebrun/colors.php/src/Colors/Color.php on line 197
```

I'm causing a loop somehow. Joy ;)

**Comment by TxHawks** [comment]
Is there any change to be aware of between the options that can be passed to `console` and the options that were available with `build.php` in `v.0.7.12`?

**Comment by dmolsen** [comment]
I'm 99% sure it's all backwards compatible. Outside of `watch` not working that is. Closer on the issue. It's related to `v0.4.1` of the color library. The regular dev version I have was only running `v0.3.0` and happily chugging along. I'll get it fixed.

**Comment by TxHawks** [comment]
Thanks!

**Comment by dmolsen** [comment]
Please run `composer update pattern-lab/core` in your project. The problem with `php core/console --help` should be fixed.

**Comment by TxHawks** [comment]
It's indeed fixed. Thanks!
