### ISSUE TITLE
"Working With Includes" using Twig and YAML

### ISSUE THREAD

**Issue by jorap** [pattern-lab/edition-php-twig-development#20]
Hi,

Thanks for the release of Pattern Lab 2.0 that allows Twig and YAML.
I have a question regarding "Creating Pattern-specific Values"
in "Working With Includes".

For example, I have the following files in "00-atoms"

File 1: hh1.twig
```
<h1>{{ title }}</h1>
```

File 2: hh1.yml
```
title: 'Heading 1'
```
File 3: hh2.twig
```
<h2>{{ title }}</h2>
```
File 4: hh2.yml
```
title: 'Heading 2'
```
File 5: hh.twig
```
{% include "atoms-hh1" %}
{% include "atoms-hh2" %}
```
By default, the generated HTML for hh.twig will become:
```
<h1>Pattern Lab</h1>
<h2>Pattern Lab</h2>
```
If I have a file named hh.yml, what will I need to populate in hh.yml,
so I could have the following HTML from hh.twig:
```
<h1>Heading 1</h1>
<h2>Heading 2</h2>
```
Thanks in advance.

Regards,

Jon
```

**Comment by bradfrost** [comment]
Hey @jorap,
I'm not versed in the Twig and YAML flavors of Pattern Lab, but there are a few things that I do that might be helpful. 

One solution would be to change the variable names so you can target them separately.

``` 
<h1>{{ mainTitle }}</h1>

<h2>{{ subTitle }}</h2>
```

Etc.

Or you could target the specific instance of the include. I'm not sure what the syntax is for Twig and YAML, but here's what it looks like with Mustache and JSON:

```
{{# mainTitle }}
{{> atoms-h1 }}
{{/ mainTitle }}

```

And the JSON would look like:

```
{
    "mainTitle" : {
        "title": "Heading 1"
    }
}
```

Essentially, you're wrapping the include in a name so you can target the specific instance.

**Comment by jorap** [comment]
```
Thanks for the response.

I figured it out by making changes to the twig file.
I changed File 5 with the following:

File 5: hh.twig
{% include "atoms-hh1" with { "title": h1_title } %}
{% include "atoms-hh2" with { "title": h2_title } %}

hh.yml
h1_title: Heading 1
h2_title: Heading 2

hh.json
{
  "h1_title": "Heading 1",
  "h2_title": "Heading 2"
}



```

**Comment by aleksip** [comment]
Looks like this can be closed.
