### ISSUE TITLE
View code not showing twig file

### ISSUE THREAD

**Issue by TxHawks** [pattern-lab/edition-php-twig-development#4]
It seems to be searching for a `mustache` file.

The `Twig` tab in the code drawer shows the following:
````
404 Not Found

Not Found
The requested URL /patterns/00-atoms-01-global-00-colors/00-atoms-01-global-00-colors.mustache was not found on this server.

Apache/2.4.7 (Ubuntu) Server at [url] Port 80
````

**Comment by dmolsen** [comment]
Yeah, the "code panel" Javascript is set to get a re-write here this week. I also need it more flexible to allow plug-ins to create their own panels. Thanks for the heads up on this particular issue though.

**Comment by dmolsen** [comment]
I've fixed this specific issue. Please run:

    composer update pattern-lab/styleguidekit-assets-default

Let me know if it's working for you and then I'll close this out. Thanks.

**Comment by TxHawks** [comment]
Yep, this works.
Thanks!
