### ISSUE TITLE
Ability to import Twig macros into the global scope

### ISSUE THREAD

**Issue by TxHawks** [pattern-lab/edition-php-twig-development#5]
It could have been very useful to have a way to `{% import %}`  twig files containing macros into the global scope, so that they are available from all patterns without an explicit import.

Maybey a `_macros` folder in a similar manner to [this](https://github.com/brunschgi/terrific-composer/issues/3)?

**Comment by dmolsen** [comment]
@TxHawks -

I couldn't find any code in the repo that related to that issue unfortunately. Took some time Googling but it looks like I might be able to do this from the PatternEngine. For my own reference this is the (untested, from 2011) code:

    // loop through some macro containing dir and run...
    $twig->addGlobal('base', $twig->loadTemplate('base.macro'));

I'm thinking this would exist as `source/_macros/`. Macros should be installable via Composer but it won't be required. 

There are a number of extension points I can support in Twig. Guess macros will be the first one I dive into.

**Comment by TxHawks** [comment]
This would be super useful, I'd love to see this implemented - thanks!

And thanks for all your great work on this in general.

**Comment by dmolsen** [comment]
Support for macros is now in the `dev` branch of the Twig PatternEngine. Seems like devs/designers are going to have to be careful about naming conflicts. For now macros will have to be created by hand or copied and pasted. I'll eventually get around to making them installable with Composer.

**Comment by TxHawks** [comment]
Thanks, this is great! 

Will `composer update pattern-lab/patternengine-twig` pull the changes from `dev`?
Do I just stick the macros in  `source/_macros`?

**Comment by dmolsen** [comment]
@TxHawks -

Yes to both :)

**Comment by TxHawks** [comment]
@dmolsen -
Doesn't seem to work...

I have an `image.twig` file in `_macros`, with a `{% macro landscape (src, alt) %}` defined inside it.

When I try to call `{{ image.landscape('path/to/image', 'Alt text' }}` PL is generated without an error, bot no content is rendered by the macro.

If I place `image.twig` under `_patterns/00-atoms` and import it manually with `{% import `atoms-image' as image %}, everything works fine.

**Comment by dmolsen** [comment]
image.macro should be the file name. .macro was the extension in the doc examples I worked off of.

**Comment by TxHawks** [comment]
Ooops. Sorry should have looked at the docs more carefully. Thanks

**Comment by TxHawks** [comment]
`.macro` files aren't so great for syntax highlighting... What do you think of `.macro.twig` or just `.twig`?

**Comment by dmolsen** [comment]
you know what? in looking at my code to understand why `.macro` i realized
you can change the extension in the config. go to `configs/config.ini` and
set `twigMacroExt` to whatever you like :)

On Wed, Mar 4, 2015 at 4:17 PM, TxHawks <notifications@github.com> wrote:

> .macro files aren't so great for syntax highlighting... What do you think
> of .macro.twig or just .twig?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pattern-lab/edition-php-twig-development/issues/5#issuecomment-77250281>
> .
>



-- 

http://dmolsen.com

**Comment by TxHawks** [comment]
Great!

One more thing. You write in the readme:
> **Please note:** ensure that there is no overlap between the keys 
> for your macros and the keys for your data attributes

Why? I thought macros don't have access to the template variables so there isn't a conflict

**Comment by dmolsen** [comment]
That's more theoretical then tested so feel free to try it out but...

```json
{
    "foo": {
       "bar": "baz"
    }
}
```

and `foo.macro` with a "method" "bar" are accessed via `{{ foo.bar }}`. Meaning there may be a conflict with `foo` and `foo.bar`. Again, I didn't try it.

**Comment by TxHawks** [comment]
Tested and verified. Variable set in the `_patterns` dir (either in `.twig` files using `{% set %}` or in `.json` files) override macros. Having a `foo` key in your data structure overwrites all macros defined in your `_macros/foo.macro`.

Also, for future reference, in order to change the macros extension, `twigMacroExt` needs to be set in `config/config.yml`, not `configs/config.ini`
