### ISSUE TITLE
Variable context and value inheritance 

### ISSUE THREAD

**Issue by TxHawks** [pattern-lab/edition-php-twig-development#8]
I couldn't find a way to make Twig act this way &mdash; and I'm not sure if this is a Twig design decision, or if perhaps something like that can be resolved in the php implantation of Twig &mdash; but I would have liked a variable to "understand" its scope in the context of the `json` file, and inherit values from parent scopes if not locally defined.

By "understand its context" I mean that if I have the following `teaser.twig` partial:
```twig
<article>
  <h3>{{ headline }}</h3>
  {% if byline %}
    <address>{{ byline }}</address>
  {% endif %}
</article>
```

I'd like to be able to include it like this, which could get very complex:

```twig
{% for article in articles.items %}
  {{ include('molecules-teaser') }}
{% endfor %}
```

Instead of having to do:

```twig
  {{ include('molecules-teaser', {headline: article.headline, byline: article.byline}) }}
```

Meaning, always look for the variable in the local scope first, then, if not defined, traverse up the blocks towards global scope in resolving the variable's value. This is how it works in the Mustache version of Pattern Lab, and it makes a lot of sense to me for templating.

Means you could set defaults in the model instead of in the view, enabling us to have a `json` like:

```json
{
  "headline": "Lorem ipsum",
  "articles": {
    "byline": "Author Name",
    "items": [
      {},
      {
        "headline": "Some text"
      },
      {
        "byline": "John Doe"
      }
    ]
  }
}
```

and this Twig

```twig
<!-- Inside articles -->
{% for article in articles.items %}
  {{ include('molecules-teaser') }}
{% endfor %}

<!-- Outside articles -->
{{ include('molecules-teaser') }}
```

output this html:

```html
<!-- Inside articles -->
<article>
  <h3>Lorem ipsum</h3>
  <address>Autor Name</address>
</article>

<article>
  <h3>Some text</h3>
  <address>Autor Name</address>
</article>

<article>
  <h3>Lorem ipsum</h3>
  <address>John Doe</address>
</article>

<!-- Outside articles -->
<article>
  <h3>Lorem ipsum</h3>
</article>
```

Phew, this came out long, sorry. Hope it makes any sense. 
Unless I am conceptually very wrong in my understanding of templating best practices (very plausible), this pretty much annuls the benefits of Twig over Mustache in the context of Pattern Lab for me.

**Comment by dmolsen** [comment]
@TxHawks -

This is completely untested but I'd think you'd need it to look like this:

```
{
  "article": {
     "headline": "Lorem Ipsum",
     "byline": "Author Name"
  },
  "articles": {
    "byline": "Author Name",
    "items": [
      {},
      {
        "headline": "Some text"
      },
      {
        "byline": "John Doe"
      }
    ]
  }
}
```

Because you'd have to reference the vars as `article.headline` in the molecule. And you've about reached my limit on my knowledge of Twig ;) Let me know if that works.

**Comment by TxHawks** [comment]
@dmolsen -

No, I've already thought of that, but unfortunately even that doesn't work... 

The output is

```html
<article>
  <h3></h3>
  <address></address>
</article>
  
<article>
  <h3>Some text</h3>
  <address></address>
</article>
  
<article>
  <h3></h3>
  <address>John Doe</address>
</article>
```

My knowledge of php < 0, but I would think it is an issue of how the `json` is parsed. 

I imagine that the `json` is parsed as a native php object, and when calling `article.headline` from the `for` loop, it actually looks at `articles.items[i].headline`. `article.items[0]` does not have a `headline` key, so it returns `undefined` or `null` or whatever it is php would return (sorry for my ignorance and using javascript syntax).

One way I could think of resolving this is in parsing always including the parent scope in its childern (this sounds like a horrible idea, I know).

Something like:

```json
{
  "headline": "Lorem ipsum",
  "articles": {
    "byline": "Author Name",
    "items": [
      {},
      {
        "headline": "Some text"
      },
      {
        "byline": "John Doe"
      }
    ]
  }
}
```

being parsed into the following object:
```js
{
  "headline": "Lorem ipsum",
  "articles": {
    "headline": "Lorem ipsum",        // From global scope
    "byline": "Author Name",
    "items": [                        // This is an array, so don't include parent keys directly
      {
        "headline": "Lorem ipsum",    // from 'aritcles' scope
        "byline": "Author Name",      // from 'articles' scope
      },
      {
        "headline": "Lorem ipsum",    // from 'aritcles' scope
        "byline": "Author Name",      // from 'articles' scope
        "headline": "Some text"       // from current scope, overrides inheritance
      },
      {
        "headline": "Lorem ipsum",    // from 'aritcles' scope
        "byline": "Author Name",      // from 'articles' scope
        "byline": "John Doe"          // from current scope, overrides inheritance
      }
    ]
  }
}
```

This is probably not such a great way to solve it from an architectural point of view, and because it will create huge object, but maybe a better implementation could be conceived by someone with better programming skills than mine (confession: I'm really much more a designer than a developer).

**Comment by dmolsen** [comment]
@TxHawks -

K. This uses [Twig's filters](http://twig.sensiolabs.org/doc/filters/index.html) and seems to works. This is about the best I can come up with. Have no idea how performance would stack up over time/multiple patterns/depth/etc. Let's start with the data:

```json
{
	"article": {
		"headline": "default headline",
		"byline": "default byline"
	},
	"articles": {
		"items": [
			{},
			{
				"headline": "Some text"
			},
			{
				"byline": "John Doe"
			}
		]
	}
}
```

And the `atoms-article` template:

```twig
<article>
	<h3>{{ article.headline }}</h3>
	<address>{{ article.byline }}</address>
</article>
```

And the `atoms-articles` template (obv just quick testing this):

```twig
{% for articleStore in articles.items %}
	{% set articleStore = article|merge(articleStore) %}
	{% include 'atoms-article' with { 'article': articleStore } %}
{% endfor %}
```

It's a little verbose. It does allow for the merging of the iterated content with the `article` attribute from the global context without having to set attributes individually. Note that the `include` has access to the global context regardless. It just comes down to how do we override the `article` attribute. If we don't use the `with` the `article` attribute in the global context picks up bad data.

**Comment by TxHawks** [comment]
@dmolsen  - 
Thanks for that - I did have the merge `filter` in mind, though it can become very verbose. I was hoping to come up with something as trivial as the traversing Mustache does. For some of the less technical designers on my team that would have been a great help, but I guess it would be trying to force Twig into something that it is not.

Just wanted to say again how much I appreciate you work on this project.

Since not many people are currently using the Twig version, I was wondering if there are any specific features you'd like me to test.

**Comment by dmolsen** [comment]
@TxHawks -

Yeah, looks like Twig prefers scoping and "redefining" variable names from the template. That kind of "logic" is anathema to Mustache. On what you can test... really just think about project workflow. You've already given me a number of ideas on what I need to tweak.

FWIW, I've updated a few things in core and the Twig PatternEngine. One of those things was `watch` so you may be interested in upgrading. To do so run:

    composer update pattern-lab/core
    composer update pattern-lab/patternengine-twig

**Comment by TxHawks** [comment]
@dmolsen - 
I generally use grunt for watching changes, but I'll update and test the watch function on a few systems. 

BTW, is there a place were new features of PL2 are documented? I remember something about you adding pattern-specific annotations, is that right? 
If so, I'll open another issue asking how to use them, for better searchability

**Comment by dmolsen** [comment]
@TxHawks -

No documentation. We have a plan for tackling it but I don't feel like PL2 is solid enough for me to spend time on it. Please feel free to open a new issue.
